name: test-import-export
on: [push, pull_request]

env:
  BLENDER_MAJOR: 2
  BLENDER_MINOR: 91

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Install Blender
        run: |
          echo "Looking for Blender $BLENDER_MAJOR.$BLENDER_MINOR on builder.blender.org..."
          BLENDER_URL="https://builder.blender.org$(curl -s https://builder.blender.org/download/ | \
            grep -oe '[^\"]*blender-'$BLENDER_MAJOR'\.'$BLENDER_MINOR'[^\"]*linux64[^\"]*' | \
            tail -n1)"
          echo "Downloading $BLENDER_URL"
          mkdir /opt/blender
          curl -SL "$BLENDER_URL" | \
            tar -Jx -C /opt/blender --strip-components=1
          sudo ln -s /opt/blender/blender /usr/local/bin/blender
          blender --version

      - name: Install Addon
        run: |
          ADDON_DIR=/opt/blender/$BLENDER_MAJOR.$BLENDER_MINOR/scripts/addons
          rm -rf $ADDON_DIR/io_scene_gltf2
          cp -r addons/io_scene_gltf2 $ADDON_DIR

      - name: Setup Tests
        run: |
          cd tests
          npm install

      - name: Run Tests
        run: |
          cd tests
          npm run test-bail
